# Generated by Django 2.1.5 on 2019-02-03 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingquestion',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.TextChoicesQuestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textchoice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.TextChoicesQuestion'),
            preserve_default=False,
        ),
    ]
